### ISSUE TITLE
[Fix] bantam

### ISSUE THREAD

**Issue by 4k4xs4pH1r3** [arch3rPro/PST-Bucket#14]
scoop install bantam -g
WARN  Purging previous failed installation of bantam.
ERROR 'bantam' isn't installed correctly.
Removing older version (v1.0-Beta).
'bantam' was uninstalled.
Installing 'bantam' (v1.0-Beta) [64bit] from ar bucket
The remote server returned an error: (404) Not Found.
URL https://downloads.sourceforge.net/project/pst-bucket/Bantam/bantam.zip is not valid

**Comment by arch3rPro** [comment]
fixed
