### ISSUE TITLE
[Fix] windterm

### ISSUE THREAD

**Issue by 4k4xs4pH1r3** [arch3rPro/PST-Bucket#24]
Installing 'windterm' (2.6) [64bit] from ar bucket
The remote server returned an error: (404) Not Found.
URL https://github.com/kingToolbox/WindTerm/releases/download/2.6-prerelease/WindTerm_2.6.0_Prerelease_2_Windows_Portable_x86_64.zip is not valid

**Comment by arch3rPro** [comment]
fixed
