### ISSUE TITLE
sublime-text.json源失效

### ISSUE THREAD

**Issue by Th0m4z-sec** [arch3rPro/PST-Bucket#9]
PST-Bucket/bucket/others/sublime-text.json源失效啦，报502
![1](https://github.com/arch3rPro/PST-Bucket/assets/99456113/a78c49b9-452d-4492-8b8d-1bfffdd4ee93)

**Comment by arch3rPro** [comment]
服务器到期了，网盘需要重新上传

**Comment by arch3rPro** [comment]
已修复
